server:
  port: 7003
eureka:
  instance:
    hostname:  eureka7003.com  #127.0.0.1    #eureka服务端的实例名称
  client:
    register-with-eureka: false   #不向注册中心注册自己
    fetch-registry: false         #表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:                  #集群配置，8001注册要同时注册到三台机器
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/