server:
  port: 80

eureka:
  client:
    service-url:
    #这个是eureka集群版注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false #自己不能注册